# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.0.0
    - run: sed -i 's/\/home\/runner\/work\/test\/test\///' /home/runner/work/test/test/coverage/coverage.json
    - run: sed -i 's/\/home\/runner\/work\/test\/test\///' /home/runner/work/test/test/coverage/lcov.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
